# Interval in seconds
interval: 300

# Interval in seconds
interval: 300

# The donation link
donation-link: "https://buy.stripe.com/14k8Al4ki5tl8HmfZb"

# Messages to broadcast. %link% will be replaced by the donation link.
# Supports color codes with &
messages:
  - "&d&lArthoNetwork &7» &fSoutenez le serveur : &d$link"
  - "&d&lArthoNetwork &7» &fEnvie d'aider ? Faites un don : &d$link"
  - "&a[ArthoNetwork] &2Les serveurs ne sont pas gratuits, &aaidez-nous ! &b$link"
  - "&c[ArthoNetwork] &4Un petit geste pour le serveur ? &c$link"
  - "&9[ArthoNetwork] &3Participez à l'aventure en nous soutenant : &b$link"
  - "&5[ArthoNetwork] &dMerci de votre fidélité ! &5Dons : &d$link"

# Auto-Update Configuration
update:
  check: true
  auto-download: true


auth:
  whitelist:
    kick-message: "&cVous n'êtes pas sur la whitelist !"
  messages:
    not-registered: "&c⚠ Vous devez vous enregistrer !"
    not-logged-in: "&c⚠ Vous devez vous connecter !"
    login-instruction: "&e/login <motdepasse>"
    register-instruction: "&e/register <motdepasse> <confirmation>"
    title: "&cAuthentification Requise"
    subtitle-login: "&e/login <mot de passe>"
    subtitle-register: "&e/register <mdp> <confirmation>"
    success-login: "&aVous êtes connecté !"
    success-register: "&aInscription réussie ! Vous êtes connecté."
    wrong-password: "&cMot de passe incorrect !"
    already-logged-in: "&cVous êtes déjà connecté."
    passwords-do-not-match: "&cLes mots de passe ne correspondent pas."
    already-registered: "&cVous êtes déjà enregistré ! Utilisez /login."
    not-registered-error: "&cVous n'êtes pas enregistré ! Utilisez /register."
    usage-login: "&cUsage: /login <mot de passe>"
    usage-register: "&cUsage: /register <mot de passe> <confirmation>"
    usage-changepassword: "&cUsage: /changepassword <nouveau> <confirmation>"
    password-changed: "&aVotre mot de passe a été changé avec succès !"
    force-change-required: "&c⚠ Vous devez changer votre mot de passe ! Utilisez /changepassword"
    admin-reset-success: "&aMot de passe réinitialisé pour $player. Cliquez pour copier : "
    admin-reset-hover: "&eCliquez pour copier le mot de passe"
    password-copied: "&aMot de passe copié !"
